version: '3.1'

services:

  drupal:
    image: edwinkent/catshop:latest
    ports:
      - 8080:80
    volumes:
      - .:/app/web/profiles/custom/catshop
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      # - /app/web/sites
    restart: always

  mysql:
    image:  mysql
    ports:
          - "3308:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal